name: lintbot
run-name: Linting QML for PR
on:

  workflow_run:
    workflows: [push-build-release]
    types:
      - completed
jobs:
  lint-comment:
    uses: EddyTheCo/Common/.github/workflows/lint.yml@develop
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      actions: read
      pull-requests: write
